// Application constants
const ROLES = {
  PRESIDENTE: 'PRESIDENTE',
  VOCAL: 'VOCAL',
  COORDINADOR: 'COORDINADOR',
  VOLUNTARIO: 'VOLUNTARIO'
};

const CATEGORIAS_DONACION = {
  ROPA: 'ROPA',
  ALIMENTOS: 'ALIMENTOS',
  JUGUETES: 'JUGUETES',
  UTILES_ESCOLARES: 'UTILES_ESCOLARES'
};

const ESTADOS_USUARIO = {
  ACTIVO: true,
  INACTIVO: false
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
};

const GRPC_STATUS = {
  OK: 0,
  CANCELLED: 1,
  UNKNOWN: 2,
  INVALID_ARGUMENT: 3,
  DEADLINE_EXCEEDED: 4,
  NOT_FOUND: 5,
  ALREADY_EXISTS: 6,
  PERMISSION_DENIED: 7,
  RESOURCE_EXHAUSTED: 8,
  FAILED_PRECONDITION: 9,
  ABORTED: 10,
  OUT_OF_RANGE: 11,
  UNIMPLEMENTED: 12,
  INTERNAL: 13,
  UNAVAILABLE: 14,
  DATA_LOSS: 15,
  UNAUTHENTICATED: 16
};

const ERROR_CODES = {
  // Authentication errors
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  
  // Authorization errors
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_ACCESS_DENIED',
  RESOURCE_MODIFICATION_DENIED: 'RESOURCE_MODIFICATION_DENIED',
  SELF_ASSIGNMENT_ONLY: 'SELF_ASSIGNMENT_ONLY',
  ACCESS_DENIED: 'ACCESS_DENIED',
  
  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',
  
  // Business logic errors
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVALID_DATE: 'INVALID_DATE',
  
  // Service errors
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  AUTH_SERVICE_UNAVAILABLE: 'AUTH_SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

const VALIDATION_RULES = {
  // User validation
  NOMBRE_USUARIO: {
    MIN_LENGTH: 3,
    MAX_LENGTH: 50,
    PATTERN: /^[a-zA-Z0-9_]+$/
  },
  NOMBRE: {
    MIN_LENGTH: 2,
    MAX_LENGTH: 100,
    PATTERN: /^[a-zA-ZáéíóúÁÉÍÓÚñÑ\s]+$/
  },
  EMAIL: {
    PATTERN: /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  },
  TELEFONO: {
    PATTERN: /^[\d\s\-\+\(\)]+$/,
    MIN_LENGTH: 8,
    MAX_LENGTH: 20
  },
  
  // Donation validation
  DESCRIPCION: {
    MIN_LENGTH: 5,
    MAX_LENGTH: 500
  },
  CANTIDAD: {
    MIN: 1,
    MAX: 999999
  },
  
  // Event validation
  NOMBRE_EVENTO: {
    MIN_LENGTH: 5,
    MAX_LENGTH: 255
  },
  DESCRIPCION_EVENTO: {
    MIN_LENGTH: 10,
    MAX_LENGTH: 1000
  }
};

module.exports = {
  ROLES,
  CATEGORIAS_DONACION,
  ESTADOS_USUARIO,
  HTTP_STATUS,
  GRPC_STATUS,
  ERROR_CODES,
  VALIDATION_RULES
};